### ISSUE TITLE
Problems getting started

### ISSUE THREAD

**Issue by benedikt-buchert** [BurdaMagazinOrg/thunder-project#17]
After running:

`composer create-project burdamagazinorg/thunder-project my-project --stability dev --no-interaction`

I get the following error:

```
178d32195253207cc74097296e25079a23f0b2e5 is gone (history was rewritten?)

[RuntimeException]                                                           
  Failed to execute git checkout '178d32195253207cc74097296e25079a23f0b2e5' -  
  - && git reset --hard '178d32195253207cc74097296e25079a23f0b2e5' --          
  fatal: reference is not a tree: 178d32195253207cc74097296e25079a23f0b2e5   
```

What am I doing wrong?

**Comment by benedikt-buchert** [comment]
This helped me:

https://github.com/acquia/lightning-project/issues/17

**Comment by mtodor** [comment]
It's some issue with composer and yes: `--no-install` option with `composer install` after helps.

It could be related to composer cache too, where some commit IDs are available in the cache, but not in git or something like that. I'm not sure.
