### ISSUE TITLE
Cannot install, missing default.settings.php file

### ISSUE THREAD

**Issue by loziju** [BurdaMagazinOrg/thunder-project#4]
I'm new to D8, to composer and to using `composer create-project`. However, I did try composer create for D8 and had no issue. For thunder, though, I encountered the following problem:

![](http://cl.ly/3f050A1r3K31/iTerm2%20-%201.%20bash%20-%20Screen%20Shot%2011%20Dec%202016%206.31.47%20pm.png)

Is it something that I missed out?

**Comment by dbosen** [comment]
Hi!
Did you get another warning or failure message during the create project process? Could you try and enter the created directory and do a "composer install" inside that directory?

**Comment by dbosen** [comment]
Oh, and please try again to do 
`composer create-project burdamagazinorg/thunder-project MYPROJECT --stability dev --no-interaction `

We updated the drupal-scaffold module

**Comment by loziju** [comment]
Hey @dbosen all seems well after you updated the drupal-scaffold module. Thanks! Btw, composer install didn't work, tried it out yesterday.
