### ISSUE TITLE
Add .htaccess to this repository

### ISSUE THREAD

**Issue by oleksii-kufliievskyi** [BurdaMagazinOrg/thunder-project#6]
readme.md provides us with `Usage` section & `Installing Thunder` section.
But since Drupal moved to `docroot` folder, it's required to add .htaccess with custom 'RewriteRule' commands.

If we don't use .htaccess for this `project template` we will have urls with `docroot`. This is not good at all as I think.

I have tried to make it work with my custom .htaccess file. See it below : 

```.htaccess
Options -Indexes
Options +FollowSymLinks
RewriteEngine on

# invoke rewrite engine
RewriteEngine On
RewriteBase /docroot/
RewriteRule .* docroot/$0 [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule .* docroot/index.php?q=$0 [QSA]
```

It works correctly for me only on frontend part.
If I submit any form in the admin panel , for example `Channel settings for Article `, url is  /admin/structure/types/manage/article/fields/node.article.field_channel

I see error : 
```
Redirects to external URLs are not allowed by default, use \Drupal\Core\Routing\TrustedRedirectResponse for it.
```

I will continue checking my .htaccess and I hope I will find the way how to fix it. But I will really appreciate if you can advise me or add .htaccess file to this repository.

Thanks in advance.

**Comment by dbosen** [comment]
Hi!
If composer create did not install the .htaccess file, try running composer install or composer update. Both  will install a correct .htaccess file into the docroots directory. 
You should point your apache webserver to the docroot directory and everything should work.

**Comment by oleksii-kufliievskyi** [comment]
@dbosen Thank you for your answer, now I understand how it works.
