### ISSUE TITLE
blazy.min.js missing (library folder)

### ISSUE THREAD

**Issue by miscs** [BurdaMagazinOrg/thunder-project#9]
Hi all,

after running `composer create-project burdamagazinorg/thunder-project MYPROJECT --stability dev --no-interaction` arcticle header images weren´t loading (e.g in the demo article the thunder city image) only the blue loading indicator was spinning endlessly. This was because blazy.min.js was missing.

I checked the download-bundle from drupal.org/projects/thunder and found the files in the folder profiles/thunder/libraries. On my new installation this folder was missing, so I copied the whole folder to profiles/contrib/thunder/libraries in my installation.

Would it be possible to integrate these files, so that after `composer create-project burdamagazinorg/thunder-project MYPROJECT --stability dev --no-interaction` all runs smooth, or did I messed something up?

Thanks!

**Comment by dbosen** [comment]
Hello,
you need to install node first. Then composer will install the required frontend libraries with bower. See https://github.com/BurdaMagazinOrg/thunder-project for more information on the needed prerequisites for install thunder with composer.

**Comment by miscs** [comment]
Thanks! My bad, bower was somehow not working...
